@php
    $baseUrl= 'http://localhost:8000'
@endphp

@extends('layouts.master')

@section('title')
    <title>Tin tuc | Truoc khi tiem chung</title>
@endsection

@section('css')
@endsection

@section('js')<!--/phan rieng-->
@endsection

@section('content')
    <hr>
    <section>
        <div class="container">
            <div class="row">
                @php
                    $baseUrl= 'http://localhost:8000'
                @endphp
                <div class="col-sm-12 padding-right">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-4">
                            <div class="view-product">
                                <img object-fit="none"
                                     src="/eshopper/images/home/8yQz9RriqsZIQOyhS2m8.png"
                                     alt=""/>
                            </div>

                        </div>
                        <div class="col-sm-8">
                            <div class="product-information"><!--/product-information-->
                                <h2>Lịch tiêm chủng cho trẻ 7-18 tuổi theo khuyến nghị của CDC (Hoa Kỳ)</h2>
                                <p>Nguồn tham khảo: Cdc.gov</p>
                                <span>

                                        Những vấn đề cần biết trước khi tiêm chủng
                                </span>

                                <p><b>Lần cuối cập nhật:</b> 2021-07-03 20:49:51</p>
                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->
                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <h2 class="title text-center">Thông tin
                        </div>
                        <div class="tab-content">

                            <div class="tab-pane fade active in" id="reviews">
                                <div class="col-sm-12">
                                    <ul>
                                        <li><a href=""><i class="fa fa-user"></i>PV Vaccination</a></li>
                                        <li><a href=""><i
                                                    class="fa fa-clock-o"></i> 20:42:51
                                            </a></li>
                                        <li><a href=""><i
                                                    class="fa fa-calendar-o"></i> 2021-07-03
                                            </a></li>
                                    </ul>
                                    <div class="rich-text" style="box-sizing: border-box; caret-color: #333333; color: #333333; font-family: Helvetica, Arial, san-serif; font-size: 15px; text-size-adjust: auto;">
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px;"><span style="box-sizing: border-box; font-weight: bold;">Để biết ch&iacute;nh x&aacute;c loại vắc xin v&agrave; thời điểm n&agrave;o ti&ecirc;m vắc xin ph&ugrave; hợp cho trẻ từ 7 đến 18 tuổi, b&aacute;c sĩ sẽ phải dựa tr&ecirc;n t&igrave;nh trạng sức khỏe, t&igrave;nh sử bệnh tật v&agrave; c&aacute;c loại vắc xin đ&atilde; sử dụng, v&igrave; vậy c&aacute;c bậc phụ huynh cần được b&aacute;c sĩ tư vấn kỹ lưỡng trước khi ti&ecirc;m vắc xin cho trẻ.</span></p>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px;">C&aacute;c loại vắc xin trong lịch ti&ecirc;m chủng cho trẻ từ 7 đến 18 tuổi dưới đ&acirc;y được đề xuất bởi Ban Cố vấn Thực h&agrave;nh Ti&ecirc;m chủng v&agrave; được ph&ecirc; duyệt bởi Trung t&acirc;m Dự ph&ograve;ng v&agrave; Kiểm so&aacute;t bệnh tật Hoa Kỳ, Viện h&agrave;n l&acirc;m Nhi khoa Hoa Kỳ, Viện b&aacute;c sĩ gia đ&igrave;nh Mỹ v&agrave; Trường Đại học Sản Phụ khoa Hoa Kỳ.</p>
                                    </div>
                                    <h2 style="box-sizing: border-box; font-family: Helvetica, Arial, san-serif; font-weight: 500; line-height: 1.3; color: #333333; margin-top: 0px; margin-bottom: 10px; font-size: 27px; caret-color: #333333; text-size-adjust: auto;">1. Lịch ti&ecirc;m chủng d&agrave;nh cho trẻ từ 7 đến 18 tuổi</h2>
                                    <div class="rich-text" style="box-sizing: border-box; caret-color: #333333; color: #333333; font-family: Helvetica, Arial, san-serif; font-size: 15px; text-size-adjust: auto;">
                                        <ul style="box-sizing: border-box; margin: 0px 0px 15px 20px;">
                                            <li style="box-sizing: border-box; margin: 0px 0px 15px;">Tất cả c&aacute;c trẻ từ 7 đến 18 tuổi n&ecirc;n<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">ti&ecirc;m chủng ngừa c&uacute;m</span><span class="Apple-converted-space">&nbsp;</span>h&agrave;ng năm.</li>
                                            <li style="box-sizing: border-box; margin: 0px 0px 15px;">Tất cả trẻ từ 11 đến 12 tuổi n&ecirc;n ti&ecirc;m một mũi vắc-xin kết hợp ngừa vi&ecirc;m m&agrave;ng n&atilde;o cầu khuẩn (MenACWY) v&agrave; ti&ecirc;m nhắc lại khi trẻ 16 tuổi.</li>
                                            <li style="box-sizing: border-box; margin: 0px 0px 15px;">Thanh thiếu ni&ecirc;n 16 tuổi 18 c&oacute; thể ti&ecirc;m chủng ngừa bằng vắc-xin vi&ecirc;m M&agrave;ng N&atilde;o Nh&oacute;m Huyết Thanh B (MenB).</li>
                                        </ul>
                                    </div>
                                    <h2 style="box-sizing: border-box; font-family: Helvetica, Arial, san-serif; font-weight: 500; line-height: 1.3; color: #333333; margin-top: 0px; margin-bottom: 10px; font-size: 27px; caret-color: #333333; text-size-adjust: auto;">2. Vắc xin d&agrave;nh cho trẻ từ 7 đến 18 tuổi ph&ograve;ng ngừa những bệnh n&agrave;o?</h2>
                                    <div class="rich-text" style="box-sizing: border-box; caret-color: #333333; color: #333333; font-family: Helvetica, Arial, san-serif; font-size: 15px; text-size-adjust: auto;">
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; color: inherit; margin-top: 0px; margin-bottom: 10px; font-size: 22px;">2.1 Bạch hầu (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc xin Tdap)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/benh/bach-hau-4743/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Bạch hầu</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; một bệnh do vi khuẩn rất dễ l&acirc;y lan, ảnh hưởng đến hệ h&ocirc; hấp, bao gồm cả phổi. Vi khuẩn bạch hầu c&oacute; thể l&acirc;y từ người sang người khi tiếp x&uacute;c trực tiếp với những giọt nước từ người bị nhiễm bệnh khi họ ho hoặc hắt hơi. Khi nhiễm bệnh, vi khuẩn c&oacute; thể sản sinh độc tố trong cơ thể tạo ra một lớp phủ d&agrave;y ở ph&iacute;a sau mũi hoặc cổ họng khiến bạn kh&oacute; thở hoặc nuốt. Ảnh hưởng từ độc tố n&agrave;y cũng c&oacute; thể dẫn đến vi&ecirc;m cơ tim do ngộ độc, thường xảy ra với triệu chứng nhịp tim nhanh, đặc biệt c&oacute; thể rối loạn dẫn truyền dẫn tới ngừng tim v&agrave; tử vong. Trong trường hợp nghi&ecirc;m trọng, bạch hầu c&oacute; thể g&acirc;y h&ocirc;n m&ecirc;, liệt hoặc thậm ch&iacute; tử vong.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; color: inherit; margin-top: 0px; margin-bottom: 10px; font-size: 22px;">2.2 Vi&ecirc;m gan A (Ph&ograve;ng ngừa bằng vắc-xin HepA)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/benh/viem-gan-a-3128/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Vi&ecirc;m gan A</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; bệnh nhiễm tr&ugrave;ng ở gan do virus vi&ecirc;m gan A g&acirc;y ra. Vi-r&uacute;t l&acirc;y lan chủ yếu từ người sang người qua đường ph&acirc;n-miệng. N&oacute;i c&aacute;ch kh&aacute;c, vi-r&uacute;t được đưa v&agrave;o bằng miệng khi tiếp x&uacute;c với đồ vật, thực phẩm hoặc đồ uống bị nhiễm ph&acirc;n của người bị nhiễm bệnh. C&aacute;c triệu chứng c&oacute; thể bao gồm sốt, mệt mỏi, k&eacute;m ăn, n&ocirc;n &oacute;i, đau dạ d&agrave;y v&agrave; đ&ocirc;i khi v&agrave;ng da, v&agrave;ng mắt. Đ&ocirc;i khi người bị nhiễm bệnh c&oacute; thể kh&ocirc;ng c&oacute; triệu chứng, do bị bệnh nhẹ trong một hoặc hai tuần hoặc bị nặng c&oacute; thể k&eacute;o d&agrave;i v&agrave;i th&aacute;ng, bệnh hiếm khi dẫn đến suy gan v&agrave; tử vong.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.3 Vi&ecirc;m gan B (Ph&ograve;ng ngừa bằng vắc-xin HepB)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/viem-gan-b-la-gi-cach-phong-tranh-benh-hieu-qua/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Vi&ecirc;m gan B</span></a><span class="Apple-converted-space">&nbsp;</span>g&acirc;y ra c&aacute;c triệu chứng gần tương tự như bệnh c&uacute;m với cảm gi&aacute;c ch&aacute;n ăn, buồn n&ocirc;n, n&ocirc;n &oacute;i ph&aacute;t ban, đau khớp v&agrave; v&agrave;ng da. C&aacute;c triệu chứng của vi&ecirc;m gan B cấp t&iacute;nh bao gồm sốt, mệt mỏi, ch&aacute;n ăn, buồn n&ocirc;n, n&ocirc;n, đau khớp v&agrave; đau dạ d&agrave;y, nước tiểu sẫm m&agrave;u, ph&acirc;n m&agrave;u x&aacute;m v&agrave; v&agrave;ng da.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.4 Papillomavirus ở người (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc-xin HPV)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;">Si&ecirc;u vi papilon ở người (Human papillomavirus &ndash; HPV) l&agrave; một loại virus phổ biến v&agrave; l&agrave; bệnh l&acirc;y qua đường t&igrave;nh dục (Sexually transmitted infection &ndash; STI) phổ biến nhất đặc biệt ở người, đặc biệt l&agrave; thanh thiếu ni&ecirc;n v&agrave; người chưa đến 20 tuổi. Bạn c&oacute; thể bị nhiễm HPV khi quan hệ t&igrave;nh dục qua đường miệng, &acirc;m đạo hoặc hậu m&ocirc;n với người bị nhiễm virus. Bệnh thường l&acirc;y lan trong qu&aacute; tr&igrave;nh quan hệ t&igrave;nh dục qua &acirc;m đạo hoặc hậu m&ocirc;n. HPV c&oacute; thể bị l&acirc;y lan ngay cả khi người bệnh kh&ocirc;ng c&oacute; dấu hiệu hay triệu chứng g&igrave;. Khoảng 14 triệu người, bao gồm cả thanh thiếu ni&ecirc;n bị nhiễm<span class="Apple-converted-space">&nbsp;</span><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/hpv-virus-la-gi-co-bao-nhieu-chung/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">vi-r&uacute;t HPV</span></a><span class="Apple-converted-space">&nbsp;</span>mỗi năm. Nhiễm tr&ugrave;ng HPV c&oacute; thể g&acirc;y ung thư cổ tử cung, &acirc;m đạo v&agrave; &acirc;m hộ ở phụ nữ v&agrave; ung thư dương vật ở nam giới. HPV cũng c&oacute; thể g&acirc;y ung thư hậu m&ocirc;n, ung thư v&ograve;m họng v&agrave; mụn c&oacute;c sinh dục ở cả nam v&agrave; nữ.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.5 C&uacute;m (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc xin c&uacute;m h&agrave;ng năm)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/benh/cum-3162/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">C&uacute;m</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; một bệnh nhiễm tr&ugrave;ng do virus rất dễ l&acirc;y nhiễm ở mũi, họng v&agrave; phổi. Vi-r&uacute;t dễ d&agrave;ng l&acirc;y lan qua c&aacute;c giọt khi người nhiễm bệnh khi họ ho hoặc hắt hơi v&agrave; bệnh diễn tiến biến từ từ nhẹ đến nặng. C&aacute;c triệu chứng điển h&igrave;nh bao gồm sốt cao đột ngột, ớn lạnh, ho khan, nhức đầu, sổ mũi, đau họng v&agrave; đau cơ v&agrave; khớp. Mệt mỏi cực độ c&oacute; thể k&eacute;o d&agrave;i từ v&agrave;i ng&agrave;y đến v&agrave;i tuần. C&uacute;m c&oacute; thể dẫn đến nhập viện hoặc thậm ch&iacute; tử vong, ngay cả ở những trẻ khỏe mạnh trước đ&acirc;y.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.6 Bệnh sởi (Ph&ograve;ng ngừa bằng vắc-xin MMR)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/benh-soi-nguyen-nhan-trieu-chung-cach-phong-tranh/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Bệnh Sởi</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; một trong những bệnh truyền nhiễm dễ l&acirc;y lan nhất. Virus sởi l&acirc;y lan qua tiếp x&uacute;c trực tiếp với kh&ocirc;ng kh&iacute; thở của người nhiễm bệnh. Bệnh sởi dễ l&acirc;y lan đến nỗi chỉ cần ở trong c&ugrave;ng ph&ograve;ng người bị sởi, mặc d&ugrave; người đ&oacute; đ&atilde; rời đi th&igrave; kh&ocirc;ng kh&iacute; trong ph&ograve;ng cũng c&oacute; thể g&acirc;y nhiễm tr&ugrave;ng cho những người c&ograve;n lại. C&aacute;c triệu chứng thường bao gồm ph&aacute;t ban, sốt, ho v&agrave; đỏ, chảy nước mắt. Sốt c&oacute; thể dai dẳng, ph&aacute;t ban c&oacute; thể k&eacute;o d&agrave;i đến một tuần v&agrave; ho c&oacute; thể k&eacute;o d&agrave;i khoảng 10 ng&agrave;y. Biến chứng của bệnh sởi g&acirc;y vi&ecirc;m phổi, co giật, tổn thương n&atilde;o hoặc tử vong.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.7 Bệnh vi&ecirc;m m&agrave;ng n&atilde;o m&ocirc; cầu (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc-xin n&atilde;o m&ocirc; cầu)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;">Bệnh<span class="Apple-converted-space">&nbsp;</span><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/benh-viem-mang-nao-mo-cau-la-benh-gi-nguyen-nhan-trieu-chung-cach-phong-tranh/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">vi&ecirc;m m&agrave;ng n&atilde;o m&ocirc; cầu</span></a><span class="Apple-converted-space">&nbsp;</span>dẫn đến hai hậu quả: (1) vi&ecirc;m m&agrave;ng n&atilde;o (nhiễm tr&ugrave;ng m&agrave;ng n&atilde;o v&agrave; tủy sống) v&agrave; (2) nhiễm tr&ugrave;ng m&aacute;u. Vi khuẩn g&acirc;y bệnh vi&ecirc;m m&agrave;ng n&atilde;o m&ocirc; cầu khuẩn truyền từ người sang người qua những giọt tiết dịch h&ocirc; hấp hoặc từ cổ họng ph&oacute;ng ra ngo&agrave;i kh&ocirc;ng kh&iacute;. Tiếp x&uacute;c gần v&agrave; d&agrave;i kỳ như h&ocirc;n, hắt hơi hoặc ho v&agrave;o ai đ&oacute;, hoặc sống gần người bệnh, d&ugrave;ng chung đồ ăn thức uống, hay đồ vật sinh hoạt với người mang bệnh dễ bị l&acirc;y lan. C&aacute;c triệu chứng khởi ph&aacute;t như đột ngột sốt, đau đầu v&agrave; cứng cổ. Với nhiễm tr&ugrave;ng m&aacute;u, triệu chứng gồm ph&aacute;t ban m&agrave;u t&iacute;m sẫm. Tỷ lệ tử vong khoảng 1/10 người v&agrave; những điều trị th&agrave;nh c&ocirc;ng th&igrave; c&oacute; thể bị mất tay hoặc ch&acirc;n, bị điếc, c&oacute; vấn đề với hệ thống thần kinh, co giật hoặc đột quỵ.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.8 Quai bị (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc-xin MMR)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/benh-quai-bi-nguyen-nhan-trieu-chung-bien-chung-va-cach-phong-ngua/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Quai bị</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; một bệnh truyền nhiễm do virus quai bị g&acirc;y ra, l&acirc;y lan trong kh&ocirc;ng kh&iacute; do ho hoặc hắt hơi từ người bị nhiễm bệnh. Ngo&agrave;i ra, trẻ cũng c&oacute; thể bị nhiễm quai bị bằng c&aacute;ch tiếp x&uacute;c với đồ vật bị &ocirc; nhiễm như đồ chơi ở nh&agrave; trẻ. Virus quai bị g&acirc;y ra sưng tuyến nước bọt dưới tai hoặc h&agrave;m, sốt, đau cơ, mệt mỏi, đau bụng v&agrave; ch&aacute;n ăn. Biến chứng nặng đối với trẻ bị quai bị gồm vi&ecirc;m m&agrave;ng n&atilde;o (nhiễm tr&ugrave;ng m&agrave;ng n&atilde;o v&agrave; tủy sống), vi&ecirc;m n&atilde;o, mất th&iacute;nh gi&aacute;c vĩnh viễn hoặc sưng tinh ho&agrave;n, hiếm khi dẫn đến giảm khả năng sinh sản sau n&agrave;y.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.9 Ho g&agrave; (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc-xin Tdap)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/benh-ho-ga-nguyen-nhan-trieu-chung-bien-chung-va-cach-dieu-tri/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Ho g&agrave;</span></a><span class="Apple-converted-space">&nbsp;</span>l&acirc;y lan rất dễ l&acirc;y qua ho v&agrave; hắt hơi. Ho n&agrave;y c&oacute; thể k&eacute;o d&agrave;i trong nhiều tuần, khiến học sinh v&agrave; sinh vi&ecirc;n phải nghỉ học v&agrave; ngừng tham gia c&aacute;c hoạt động kh&aacute;c. Ho g&agrave; c&oacute; thể g&acirc;y tử vong cho trẻ qu&aacute; nhỏ khi chưa đến thời điểm ti&ecirc;m vắc-xin. Th&ocirc;ng thường c&aacute;c em b&eacute; bị ho g&agrave; từ anh chị của m&igrave;nh hoặc những người kh&aacute;c trong gia đ&igrave;nh. Trẻ bị ho g&agrave; c&oacute; thể bị vi&ecirc;m phổi, co giật, tổn thương n&atilde;o hoặc thậm ch&iacute; tử vong.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.10 Bệnh phế cầu khuẩn (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc-xin phế cầu khuẩn)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;">Vi&ecirc;m phổi l&agrave; bệnh nhiễm tr&ugrave;ng phổi c&oacute; thể do vi khuẩn c&oacute; t&ecirc;n l&agrave;<span class="Apple-converted-space">&nbsp;</span><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/nhung-dieu-can-biet-ve-vac-xin-phe-cau-synflorix/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">phế cầu khuẩn</span></a>. C&aacute;c loại vi khuẩn n&agrave;y cũng g&acirc;y ra c&aacute;c loại nhiễm tr&ugrave;ng kh&aacute;c, như nhiễm tr&ugrave;ng tai, nhiễm tr&ugrave;ng xoang, vi&ecirc;m m&agrave;ng n&atilde;o (nhiễm tr&ugrave;ng m&agrave;ng n&atilde;o v&agrave; tủy sống ) v&agrave; nhiễm tr&ugrave;ng m&aacute;u. Nhiễm tr&ugrave;ng xoang, nhiễm tr&ugrave;ng tai thường diễn ra nhẹ v&agrave; phổ biến hơn nhiều so với bệnh nghi&ecirc;m trọng kh&aacute;c do phế cầu g&acirc;y ra. Tuy nhi&ecirc;n, trong một số trường hợp, bệnh phế cầu khuẩn c&oacute; thể g&acirc;y tử vong hoặc dẫn đến c&aacute;c biến chứng l&acirc;u d&agrave;i như tổn thương n&atilde;o v&agrave; giảm th&iacute;nh lực. C&aacute;c vi khuẩn g&acirc;y bệnh phế cầu khuẩn l&acirc;y lan khi người bệnh ho hoặc hắt hơi. Nhiều người c&oacute; vi khuẩn trong mũi hoặc cổ họng nhưng kh&ocirc;ng bị bệnh, được gọi l&agrave; người mang mầm bệnh v&agrave; ch&iacute;nh những người n&agrave;y c&oacute; thể l&acirc;y bệnh cho người kh&aacute;c.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.11 Bệnh bại liệt (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m ph&ograve;ng IPV)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/benh/bai-liet-3109/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Bệnh bại liệt</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; một bệnh nhiễm virus cấp t&iacute;nh l&acirc;y truyền theo đường ti&ecirc;u ho&aacute; do virus Polio (Poliovirus) g&acirc;y n&ecirc;n, c&oacute; thể lan truyền th&agrave;nh dịch. Bệnh l&acirc;y qua tiếp x&uacute;c với ph&acirc;n của người bị nhiễm bệnh v&agrave; qua những giọt nước khi người bệnh hắt hơi hoặc ho. C&aacute;c triệu chứng thường bao gồm đau họng, sốt, mệt mỏi, buồn n&ocirc;n, đau đầu hoặc đau dạ d&agrave;y. Trong khoảng 1% trường hợp, bệnh bại liệt c&oacute; thể g&acirc;y liệt mềm cấp. Trong số những người bị liệt, c&oacute; khoảng 2 đến 10 trẻ trong số 100 bị tử vong do virus ảnh hưởng đến c&aacute;c cơ h&ocirc; hấp.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.12 Rubella (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc-xin MMR)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/benh-rubella-nguyen-nhan-trieu-chung-bien-chung-va-cach-de-phong/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;"><br class="Apple-interchange-newline" />Bệnh Rubella</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; do một loại virus l&acirc;y khi người bệnh ho v&agrave; hắt hơi. Ở trẻ em, rubella thường g&acirc;y ra bệnh nhẹ với sốt, sưng hạch v&agrave; ph&aacute;t ban k&eacute;o d&agrave;i khoảng 3 ng&agrave;y. Rubella hiếm khi g&acirc;y ra biến chứng nghi&ecirc;m trọng ở trẻ em, nhưng c&oacute; thể rất nghi&ecirc;m trọng đối với thai nhi trong bụng mẹ. Nếu phụ nữ mang thai bị nhiễm bệnh, Rubella c&oacute; thể g&acirc;y sẩy thai, dị tật tim nghi&ecirc;m trọng, chậm ph&aacute;t triển tr&iacute; tuệ, mất th&iacute;nh gi&aacute;c v&agrave; mất thị lực.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.13 Uốn v&aacute;n (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m vắc-xin Tdap)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/benh/uon-van-3130/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Uốn v&aacute;n</span></a><span class="Apple-converted-space">&nbsp;</span>chủ yếu ảnh hưởng đến cổ v&agrave; bụng. Khi người bị nhiễm bệnh, vi khuẩn sản sinh ra độc tố khiến cơ bắp trở n&ecirc;n căng cứng, rất đau đớn. Điều n&agrave;y c&oacute; thể dẫn đến kh&oacute;a chặt h&agrave;m khiến người bệnh kh&ocirc;ng thể mở miệng, nuốt hoặc thở. Vi khuẩn g&acirc;y bệnh uốn v&aacute;n được t&igrave;m thấy trong đất, bụi v&agrave; ph&acirc;n. Vi khuẩn x&acirc;m nhập v&agrave;o cơ thể th&ocirc;ng qua một vết đ&acirc;m, cắt hoặc xước tr&ecirc;n da. Người bệnh phục hồi ho&agrave;n to&agrave;n từ uốn v&aacute;n c&oacute; thể mất v&agrave;i th&aacute;ng với tỷ lệ tử vong l&agrave; 1 đến 2 người tr&ecirc;n 10 người mắc bệnh uốn v&aacute;n.</p>
                                        <h3 style="box-sizing: border-box; font-weight: 500; line-height: 1.3; margin-top: 0px; margin-bottom: 10px; font-size: 22px; text-size-adjust: auto;">2.14 Thủy đậu (Ph&ograve;ng ngừa bằng c&aacute;ch ti&ecirc;m ph&ograve;ng thủy đậu)</h3>
                                        <p style="box-sizing: border-box; margin: 0px 0px 15px; text-size-adjust: auto;"><a class="link-in-body" style="box-sizing: border-box; background-color: transparent; color: #0066a6; text-decoration-line: none; transition: all 0.1s ease 0s;" href="https://www.vinmec.com/vi/tin-tuc/thong-tin-suc-khoe/benh-thuy-dau-nguyen-nhan-trieu-chung-bien-chung-va-cach-dieu-tri/"><span class="link-in-body" style="box-sizing: border-box; font-weight: bold;">Thủy đậu</span></a><span class="Apple-converted-space">&nbsp;</span>l&agrave; do virus varicella zoster g&acirc;y ra. Thủy đậu rất dễ l&acirc;y lan khi người bệnh ho hoặc hắt hơi hoặc l&acirc;y từ c&aacute;c mụn nước tr&ecirc;n da khi người khỏe mạnh chạm v&agrave;o ch&uacute;ng hoặc h&iacute;t phải virus n&agrave;y. C&aacute;c triệu chứng điển h&igrave;nh của bệnh thủy đậu bao gồm ph&aacute;t ban ngứa với mụn nước, mệt mỏi, đau đầu v&agrave; sốt. Thủy đậu thường diễn biến nhẹ, nhưng n&oacute; c&oacute; thể dẫn đến nhiễm tr&ugrave;ng da nghi&ecirc;m trọng, vi&ecirc;m phổi, vi&ecirc;m n&atilde;o hoặc thậm ch&iacute; tử vong.</p>


                                    </div>
                            </div>

                        </div>
                    </div><!--/category-tab-->
                </div>
            </div>
        </div>
    </section>

    <hr>
@endsection
