@php
    $baseUrl= 'http://localhost:8000'
@endphp

@extends('layouts.master')

@section('title')
    <title>Tin tuc | Sau khi tiem chung</title>
@endsection

@section('css')
@endsection

@section('js')<!--/phan rieng-->
@endsection

@section('content')
    <hr>
    <section>
        <div class="container">
            <div class="row">
                @php
                    $baseUrl= 'http://localhost:8000'
                @endphp
                <div class="col-sm-12 padding-right">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-4">
                            <div class="view-product">
                                <img object-fit="none"
                                     src="/eshopper/images/home/eV1426OWYvW8FbjiBZkD.jpg"
                                     alt=""/>
                            </div>

                        </div>
                        <div class="col-sm-8">
                            <div class="product-information"><!--/product-information-->
                                <h2>Tác dụng phụ sau khi tiêm vaccine Covid-19: Phản ứng không đáng kể</h2>
                                <p>Nguồn tham khảo: VNVC</p>
                                <span>

                                        Những vấn đề cần biết sau khi tiêm chủng
                                </span>

                                <p><b>Lần cuối cập nhật:</b> 2021-07-03 22:58:51</p>
                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->
                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <h2 class="title text-center">Thông tin
                        </div>
                        <div class="tab-content">

                            <div class="tab-pane fade active in" id="reviews">
                                <div class="col-sm-12">
                                    <ul>
                                        <li><a href=""><i class="fa fa-user"></i>PV Vaccination</a></li>
                                        <li><a href=""><i
                                                    class="fa fa-clock-o"></i> 22:58:51
                                            </a></li>
                                        <li><a href=""><i
                                                    class="fa fa-calendar-o"></i> 2021-07-03
                                            </a></li>
                                    </ul>
                                    <p><span style="caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-align: justify; text-size-adjust: auto;">Hầu hết<span class="Apple-converted-space">&nbsp;</span></span><span style="box-sizing: border-box; font-weight: bold; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-align: justify; text-size-adjust: auto;">t&aacute;c dụng phụ sau khi ti&ecirc;m vaccine Covid-19</span><span style="caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-align: justify; text-size-adjust: auto;"><span class="Apple-converted-space">&nbsp;</span>l&agrave; những phản ứng th&ocirc;ng thường li&ecirc;n quan đến phản ứng tại vị tr&iacute; ti&ecirc;m v&agrave; c&aacute;c triệu chứng &ldquo;giả c&uacute;m&rdquo; như đau đầu, ớn lạnh, mệt mỏi, buồn n&ocirc;n, sốt, ch&oacute;ng mặt, đau cơ, nhịp tim nhanh&hellip;&nbsp; C&aacute;c triệu chứng n&agrave;y xảy ra sớm sau khi ti&ecirc;m vắc xin, tự khỏi v&agrave; kh&ocirc;ng g&acirc;y ra vấn đề nghi&ecirc;m trọng về sức khỏe cũng như kh&ocirc;ng để lại di chứng. Theo c&aacute;c chuy&ecirc;n gia,<span class="Apple-converted-space">&nbsp;</span></span><em style="box-sizing: border-box; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-align: justify; text-size-adjust: auto;">phản ứng sau ti&ecirc;m chủng vắc xin ph&ograve;ng virus corona</em><span style="caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-align: justify; text-size-adjust: auto;"><span class="Apple-converted-space">&nbsp;</span>thậm ch&iacute; l&agrave; c&oacute; lợi v&igrave; đ&oacute; l&agrave; dấu hiệu cho thấy cơ thể đ&atilde; c&oacute; đ&aacute;p ứng miễn dịch đối với vắc xin.</span></p>
                                    <h2 id="ftoc-heading-1" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 30px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">Vaccine Covid-19 l&agrave; g&igrave;?</span></h2>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;"><a style="box-sizing: border-box; background-color: transparent; color: #337ab7; text-decoration-line: none; outline: none !important;" href="https://vnvc.vn/vaccine-covid-19/" target="_blank" rel="noopener noreferrer">Vaccine ph&ograve;ng Covid-19</a><span class="Apple-converted-space">&nbsp;</span>l&agrave; loại vaccine cung cấp kh&aacute;ng thể gi&uacute;p hệ miễn dịch của người được ti&ecirc;m chủng c&oacute; khả năng nhận biết v&agrave; ti&ecirc;u diệt virus SARS-COV-2. Đ&acirc;y l&agrave; loại virus g&acirc;y ra đại dịch tr&ecirc;n thế giới, khiến hơn 100 triệu người mắc phải, gần 2,5 triệu người tử vong, l&acirc;y lan v&agrave; bao tr&ugrave;m tất cả c&aacute;c ch&acirc;u lục v&agrave; v&ugrave;ng l&atilde;nh thổ tr&ecirc;n to&agrave;n cầu.</p>
                                    <h2 id="ftoc-heading-2" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 30px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">Tại sao bị phản ứng phụ nhẹ sau khi ti&ecirc;m vaccine Covid-19 l&agrave; ho&agrave;n to&agrave;n b&igrave;nh thường?</span></h2>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Phản ứng sau ti&ecirc;m chủng hay sự cố bất lợi sau ti&ecirc;m chủng được định nghĩa l&agrave; &ldquo;hiện tượng bất thường về sức khỏe bao gồm c&aacute;c biểu hiện tại chỗ ti&ecirc;m hoặc to&agrave;n th&acirc;n xảy ra sau ti&ecirc;m chủng, kh&ocirc;ng nhất thiết do việc sử dụng vắc xin&rdquo;.</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Giống như với tất cả c&aacute;c loại vaccine kh&aacute;c, vaccine Covid-19 c&oacute; thể g&acirc;y ra c&aacute;c phản ứng phụ, mặc d&ugrave; kh&ocirc;ng phải ai cũng gặp phải. Trong c&aacute;c nghi&ecirc;n cứu l&acirc;m s&agrave;ng, hầu hết c&aacute;c<span class="Apple-converted-space">&nbsp;</span><em style="box-sizing: border-box;">t&aacute;c dụng phụ kh&ocirc;ng mong muốn của vaccine Covid-19</em>đều ở mức độ từ nhẹ đến trung b&igrave;nh v&agrave; đều được giải quyết trong v&ograve;ng v&agrave;i ng&agrave;y. (<a style="box-sizing: border-box; background-color: transparent; color: #337ab7; text-decoration-line: none; outline: none !important;" href="https://covid19.nih.gov/treatments-and-vaccines/vaccines" target="_blank" rel="nofollow noopener noreferrer">2</a>)</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Vaccine l&agrave; an to&agrave;n, để được đưa v&agrave;o sử dụng, tất cả c&aacute;c loại vaccine Covid-19 tr&ecirc;n thế giới đều phải nghi&ecirc;n cứu để đảm bảo t&iacute;nh an to&agrave;n v&agrave; hiệu lực, cũng như trải qua qu&aacute; tr&igrave;nh kiểm định nghi&ecirc;m ngặt trước khi ti&ecirc;m rộng r&atilde;i trong cộng đồng. Sau khi ti&ecirc;m vaccine, người được ti&ecirc;m chủng c&oacute; thể gặp một số phản ứng sau ti&ecirc;m, điều n&agrave;y l&agrave; ho&agrave;n to&agrave;n b&igrave;nh thường v&agrave; nằm trong dự liệu. C&aacute;c dấu hiệu phản ứng xảy ra chứng tỏ vaccine đang k&iacute;ch th&iacute;ch cơ thể tạo phản ứng miễn dịch. Đ&acirc;y l&agrave; một phần của qu&aacute; tr&igrave;nh huấn luyện hệ miễn dịch c&aacute;ch nhận diện mục ti&ecirc;u v&agrave; ti&ecirc;u diệt virus Sars-Cov-2 nếu mắc phải.</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">T&ugrave;y theo cơ địa của từng c&aacute; thể m&agrave; vaccine c&oacute; thể g&acirc;y ra một số phản ứng kh&ocirc;ng mong muốn sau ti&ecirc;m chủng. Do đ&oacute;, việc theo d&otilde;i<span class="Apple-converted-space">&nbsp;</span><em style="box-sizing: border-box;">phản ứng phụ sau ti&ecirc;m ph&ograve;ng Covid-19</em><span class="Apple-converted-space">&nbsp;</span>l&agrave; việc l&agrave;m hết sức quan trọng.</p>
                                    <h2 id="ftoc-heading-3" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 30px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">C&aacute;c t&aacute;c dụng phụ sau khi ti&ecirc;m vaccine Covid-19 thường gặp</span></h2>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Trong c&aacute;c nghi&ecirc;n cứu l&acirc;m s&agrave;ng, hầu hết c&aacute;c<span class="Apple-converted-space">&nbsp;</span><em style="box-sizing: border-box;">t&aacute;c dụng sau khi ti&ecirc;m vắc xin Covid-19</em><span class="Apple-converted-space">&nbsp;</span>đều ở mức độ từ nhẹ đến trung b&igrave;nh v&agrave; đều sẽ tự hết trong v&agrave;i ng&agrave;y. (<a style="box-sizing: border-box; background-color: transparent; color: #337ab7; text-decoration-line: none; outline: none !important;" href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7423510/" target="_blank" rel="nofollow noopener noreferrer">3</a>)</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Phản ứng phụ rất thường gặp (&ge;10%):</p>
                                    <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">
                                        <li style="box-sizing: border-box;">T&aacute;c dụng phụ tại vị tr&iacute; ti&ecirc;m (phản ứng tại chỗ ti&ecirc;m):
                                            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;">
                                                <li style="box-sizing: border-box;">Tăng cảm gi&aacute;c đau</li>
                                                <li style="box-sizing: border-box;">Đau</li>
                                                <li style="box-sizing: border-box;">N&oacute;ng</li>
                                                <li style="box-sizing: border-box;">Đỏ</li>
                                                <li style="box-sizing: border-box;">Ngứa</li>
                                                <li style="box-sizing: border-box;">Sưng</li>
                                            </ul>
                                        </li>
                                        <li style="box-sizing: border-box;">C&aacute;c t&aacute;c dụng phụ to&agrave;n th&acirc;n (phản ứng to&agrave;n th&acirc;n):
                                            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;">
                                                <li style="box-sizing: border-box;">Cảm thấy kh&ocirc;ng khỏe (kh&oacute; chịu)</li>
                                                <li style="box-sizing: border-box;">Mệt mỏi</li>
                                                <li style="box-sizing: border-box;">Ớn lạnh hoặc cảm thấy sốt (nhiệt độ kh&ocirc;ng r&otilde;)</li>
                                                <li style="box-sizing: border-box;">Đau đầu</li>
                                                <li style="box-sizing: border-box;">Buồn n&ocirc;n</li>
                                                <li style="box-sizing: border-box;">Đau khớp hoặc đau cơ</li>
                                            </ul>
                                        </li>
                                        <li style="box-sizing: border-box;">T&aacute;c dụng phụ thường gặp (1-10%)
                                            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;">
                                                <li style="box-sizing: border-box;">Sốt (nhiệt độ đo được từ 38&deg; C/100.4&deg; F trở l&ecirc;n).</li>
                                            </ul>
                                        </li>
                                    </ul>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Theo d&otilde;i c&aacute;c phản ứng sau ti&ecirc;m tối thiểu 30 ph&uacute;t tại cơ sở ti&ecirc;m chủng để l&agrave; nguy&ecirc;n tắc cần phải tu&acirc;n thủ sau ti&ecirc;m vaccine, &aacute;p dụng cả với vaccine Covid-19, v&igrave; đ&acirc;y l&agrave; khoảng thời gian c&oacute; thể xuất hiện c&aacute;c<span class="Apple-converted-space">&nbsp;</span><em style="box-sizing: border-box;">biến chứng sau ti&ecirc;m vaccine Covid-19</em><span class="Apple-converted-space">&nbsp;</span>sớm v&agrave; nặng, như phản ứng phản vệ.</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Tại điểm ti&ecirc;m chủng, C&aacute;c trường hợp phản ứng phản vệ cần được ph&aacute;t hiện v&agrave; điều trị sớm cũng như phải được chăm s&oacute;c, theo d&otilde;i v&agrave; điều trị t&iacute;ch cực tại c&aacute;c cơ sở y tế. Trong trường hợp đ&atilde; về nh&agrave;, người được ti&ecirc;m chủng cần<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">tự theo d&otilde;i trong 48h</span><span class="Apple-converted-space">&nbsp;</span>nhằm ph&aacute;t hiện c&aacute;c biểu hiện đầu ti&ecirc;n của phản ứng phản vệ để đến ngay c&aacute;c cơ sở y tế gần nhất để được xử l&yacute; kịp thời.</p>
                                    <h2 id="ftoc-heading-4" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 30px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">T&aacute;c dụng phụ k&eacute;o d&agrave;i sau khi ch&iacute;ch ngừa vacxin Covid-19</span></h2>
                                    <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">
                                        <li style="box-sizing: border-box;">Sốt: Sốt nhẹ dưới 38 độ thường khỏi sớm, c&oacute; thể k&eacute;o d&agrave;i 1-2 ng&agrave;y. Những trường hợp sốt cao &gt; 38 độ cần theo d&otilde;i, nếu th&acirc;n nhiệt kh&ocirc;ng giảm hoặc kh&ocirc;ng đ&aacute;p ứng với c&aacute;c thuốc hạ sốt th&ocirc;ng thường cần đến gặp b&aacute;c sĩ hoặc cơ sở y tế gần nhất.</li>
                                        <li style="box-sizing: border-box;">Phản ứng tại chỗ: gồm c&aacute;c triệu chứng đỏ, sưng, chai, cứng tại chỗ ti&ecirc;m&hellip; thường tự khỏi trong v&ograve;ng v&agrave;i ng&agrave;y đến 1 tuần.</li>
                                        <li style="box-sizing: border-box;">Đau khớp: c&oacute; thể tự khỏi, một số trường hợp cần d&ugrave;ng thuốc giảm đau theo chỉ định của c&aacute;n bộ y tế.</li>
                                        <li style="box-sizing: border-box;">Hội chứng n&atilde;o, m&agrave;ng n&atilde;o cấp t&iacute;nh xuất hiện những cơn kịch ph&aacute;t, rối loạn &yacute; thức: k&eacute;o d&agrave;i 1 đến nhiều ng&agrave;y, cần đưa đến cơ sở y tế để được kh&aacute;m, điều trị.</li>
                                    </ul>
                                    <h2 id="ftoc-heading-5" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 30px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">Một số hiện tượng sốc phản vệ &iacute;t gặp sau khi ti&ecirc;m vaccine Covid-19</span></h2>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Phản ứng phản vệ l&agrave; trường hợp cực kỳ hiếm gặp, bất kỳ ai bị phản ứng phản vệ đều cần được chăm s&oacute;c y tế khẩn cấp. Trung t&acirc;m Kiểm so&aacute;t v&agrave; Ph&ograve;ng ngừa dịch bệnh Hoa Kỳ (CDC Hoa Kỳ) cảnh b&aacute;o, những người bị sốc phản vệ sau lần ti&ecirc;m vaccine Covid-19 đầu ti&ecirc;n kh&ocirc;ng n&ecirc;n ti&ecirc;m liều thứ hai. C&aacute;c triệu chứng sốc phản vệ được cảnh b&aacute;o bao gồm:</p>
                                    <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">
                                        <li style="box-sizing: border-box;">M&agrave;y đay, ph&ugrave; mạch nhanh.</li>
                                        <li style="box-sizing: border-box;">Kh&oacute; thở, tức ngực, thở r&iacute;t.</li>
                                        <li style="box-sizing: border-box;">Đau bụng hoặc n&ocirc;n.</li>
                                        <li style="box-sizing: border-box;">Tụt huyết &aacute;p hoặc ngất.</li>
                                        <li style="box-sizing: border-box;">Rối loạn &yacute; thức.</li>
                                    </ul>
                                    <h3 id="ftoc-heading-6" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 24px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">1. C&aacute;c lưu &yacute; phải nhớ về t&aacute;c dụng phụ sau khi ti&ecirc;m vaccine Covid-19</span></h3>
                                    <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">
                                        <li style="box-sizing: border-box;">Kh&ocirc;ng ti&ecirc;m vaccine với những trường hợp c&oacute; phản ứng dị ứng nghi&ecirc;m trọng với bất kỳ th&agrave;nh phần hoạt chất hoặc t&aacute; dược n&agrave;o liệt k&ecirc; trong mục th&agrave;nh phần vaccine. (<a style="box-sizing: border-box; background-color: transparent; color: #337ab7; text-decoration-line: none; outline: none !important;" href="https://www.mayoclinic.org/diseases-conditions/coronavirus/in-depth/coronavirus-vaccine/art-20484859" target="_blank" rel="nofollow noopener noreferrer">1</a>)</li>
                                        <li style="box-sizing: border-box;">Kh&ocirc;ng ti&ecirc;m vaccine cho người c&oacute; cơ địa dị ứng hoặc bệnh l&yacute; c&oacute; sẵn. Nếu kh&ocirc;ng chắc chắn về t&igrave;nh trạng dị ứng do cơ địa, h&atilde;y trao đổi với b&aacute;c sĩ để được tư vấn.</li>
                                        <li style="box-sizing: border-box;">Kh&ocirc;ng ti&ecirc;m vaccine Covid-19 khi hệ miễn dịch suy yếu (suy giảm miễn dịch) hoặc đang d&ugrave;ng thuốc l&agrave;m suy yếu hệ miễn dịch (như corticosteroid liều cao, thuốc ức chế miễn dịch hoặc thuốc ung thư).</li>
                                        <li style="box-sizing: border-box;">Kh&ocirc;ng ti&ecirc;m vaccine nếu đang bị nhiễm tr&ugrave;ng, sốt (&ge; 37,5&deg;C).</li>
                                        <li style="box-sizing: border-box;">Kh&ocirc;ng ti&ecirc;m vaccine khi c&oacute; c&aacute;c vấn đề về xuất huyết/chảy m&aacute;u hoặc bầm t&iacute;m, hoặc đang d&ugrave;ng thuốc l&agrave;m lo&atilde;ng m&aacute;u (thuốc chống đ&ocirc;ng m&aacute;u).</li>
                                    </ul>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Nếu bạn kh&ocirc;ng chắc chắn bất kỳ điều g&igrave; b&ecirc;n tr&ecirc;n, h&atilde;y trao đổi với b&aacute;c sĩ để được tư vấn trước khi chỉ định ti&ecirc;m vaccine Covid-19.</p>
                                    <h3 id="ftoc-heading-7" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 24px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">2. Lưu &yacute; sau khi ti&ecirc;m mũi vaccine Covid-19 thứ 2</span></h3>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; text-decoration-line: underline;">Theo nghi&ecirc;n cứu, ti&ecirc;m mũi 2 vắc xin Covid của c&ocirc;ng ty Astrazeneca sẽ &iacute;t c&oacute; phản ứng phụ hơn so với liều thứ 1.</span></p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Nhiều kết quả thử nghiệm l&acirc;m s&agrave;ng cho thấy, người lớn tuổi c&oacute; xu hướng &iacute;t c&oacute; t&aacute;c dụng phụ sau ti&ecirc;m đ&aacute;ng lo ngại so với người trẻ. Điều n&agrave;y c&oacute; thể g&acirc;y ra do hệ thống miễn dịch của người lớn tuổi kh&ocirc;ng c&oacute; phản ứng mạnh, hoặc nhận thức về cơn đau của người lớn tuổi đ&atilde; được n&acirc;ng cao.</p>
                                    <h3 id="ftoc-heading-8" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 24px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">3. Khi n&agrave;o n&ecirc;n gọi ngay cho b&aacute;c sĩ/bệnh viện gần nhất?</span></h3>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;"><a style="box-sizing: border-box; background-color: transparent; color: #337ab7; text-decoration-line: none; outline: none !important;" href="https://www.who.int/news-room/feature-stories/detail/side-effects-of-covid-19-vaccines" target="_blank" rel="nofollow noopener noreferrer">Tổ chức Y tế Thế giới (WHO)</a><span class="Apple-converted-space">&nbsp;</span>khẳng định, biến chứng nghi&ecirc;m trọng do vaccine g&acirc;y ra l&agrave; cực kỳ hiếm gặp, trong khi đ&oacute; lợi &iacute;ch do vaccine v&agrave; ti&ecirc;m chủng mang lại lớn hơn rất nhiều. Khi gặp c&aacute;c phản ứng phản vệ dưới đ&acirc;y, người được ti&ecirc;m vaccine cần li&ecirc;n hệ ngay với b&aacute;c sĩ hoặc bệnh viện gần nhất để được chẩn đo&aacute;n nguy&ecirc;n nh&acirc;n nhằm xử tr&iacute; v&agrave; điều trị kịp thời.</p>
                                    <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">
                                        <li style="box-sizing: border-box;">Sốt cao (&gt;38 độ): N&ecirc;n uống nhiều nước, d&ugrave;ng thuốc hạ sốt an to&agrave;n, mặc tho&aacute;ng, lau m&aacute;t với nước ấm, đảm bảo nhu cầu dịch v&agrave; dinh dưỡng.</li>
                                        <li style="box-sizing: border-box;">Co giật: Co giật c&oacute; thể k&egrave;m sốt hoặc kh&ocirc;ng, d&ugrave;ng thuốc chống co giật theo đ&uacute;ng ph&aacute;c đồ xử tr&iacute; co giật.</li>
                                        <li style="box-sizing: border-box;">&Aacute;p xe: C&oacute; thể l&agrave; &aacute;p xe v&ocirc; khuẩn hoặc &aacute;p xe nhiễm khuẩn, r&ograve; dịch. Trường hợp &aacute;p xe do nhiễm khuẩn, n&ecirc;n d&ugrave;ng thuốc kh&aacute;ng sinh điều trị.</li>
                                        <li style="box-sizing: border-box;">Nhiễm khuẩn huyết: Biến chứng trầm trọng v&agrave; nguy hiểm nhất l&agrave; sốc nhiễm tr&ugrave;ng. Cần đến bệnh viện sớm để điều trị sốc theo ph&aacute;c đồ, tr&aacute;nh c&aacute;c biến chứng.</li>
                                        <li style="box-sizing: border-box;">Phản ứng qu&aacute; mẫn cấp t&iacute;nh: Trong trường hợp phản ứng nặng n&ecirc;n xử tr&iacute; như trường hợp phản ứng phản vệ.</li>
                                        <li style="box-sizing: border-box;">Phản ứng phản vệ: do nhiều nguy&ecirc;n nh&acirc;n g&acirc;y ra, thường c&oacute; triệu chứng như vật v&atilde;, mẩn ngứa, ban đỏ, mề đay, mạch kh&oacute; bắt, huyết &aacute;p tụt, đau bụng, kh&oacute; thở, co giật&hellip; Cần đến bệnh viện ngay để được cấp cứu kịp thời.</li>
                                        <li style="box-sizing: border-box;">Huyết khối: Đau đầu dai dẳng, dữ dội, triệu chứng thần kinh khu tr&uacute;, co giật, hoặc mờ hoặc nh&igrave;n đ&ocirc;i, kh&oacute; thở hoặc đau ngực, đau bụng hoặc đau bụng dữ dội, đau, ph&ugrave; chi dưới, c&oacute; thể biểu hiện chảy m&aacute;u, xuất huyết da, hoặc xuất huyết nội tạng.</li>
                                    </ul>
                                    <h2 id="ftoc-heading-9" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 30px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">Quy tr&igrave;nh ti&ecirc;m vacxin Covid-19 tại Việt Nam b&agrave;i bản, đ&uacute;ng tiến tr&igrave;nh</span></h2>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Quy tr&igrave;nh ti&ecirc;m chủng vacxin Covid-19 tại Việt Nam được triển khai ở cấp độ an to&agrave;n mức cao nhất, tiến bộ v&agrave; khắt khe hơn rất nhiều so với c&aacute;c nước kh&aacute;c tr&ecirc;n thế giới, kể cả ở c&aacute;c nước ph&aacute;t triển.</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">C&aacute;c cơ sở ti&ecirc;m chủng vacxin Covid-19 tại Việt Nam đều được đảm ti&ecirc;u chuẩn về cơ sở vật chất, trang thiết bị v&agrave; nh&acirc;n lực. Thực hiện nghi&ecirc;m t&uacute;c c&ocirc;ng t&aacute;c kh&aacute;m s&agrave;ng lọc, tư vấn trước ti&ecirc;m chủng v&agrave; tổ chức buổi ti&ecirc;m chủng an to&agrave;n theo hướng dẫn của Bộ Y tế. Người ti&ecirc;m vaccine phải ở lại &iacute;t nhất 30 ph&uacute;t tại điểm ti&ecirc;m chủng để theo d&otilde;i c&aacute;c phản ứng sau ti&ecirc;m, được hướng dẫn theo d&otilde;i c&aacute;c phản ứng tại nh&agrave; từ 24-48 giờ.</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Ngo&agrave;i ra, c&aacute;c bệnh viện lu&ocirc;n trong tư thế sẵn s&agrave;ng, thường trực c&ocirc;ng t&aacute;c cấp cứu, lường trước c&aacute;c trường hợp<span class="Apple-converted-space">&nbsp;</span><em style="box-sizing: border-box;">biến chứng sau ti&ecirc;m vaccine virus Corona</em><span class="Apple-converted-space">&nbsp;</span>nhằm bảo đảm an to&agrave;n tối đa cho người được ti&ecirc;m.</p>
                                    <h2 id="ftoc-heading-10" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 30px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">Những c&acirc;u hỏi thường gặp về phản ứng phụ sau khi ti&ecirc;m vacxin Covid-19</span></h2>
                                    <h3 id="ftoc-heading-11" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 24px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">1. L&agrave;m g&igrave; để giảm phản ứng phụ sau khi ti&ecirc;m vacxin Covid-19</span></h3>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">C&oacute; thể sử dụng thuốc chứa paracetamol/acetaminophen nếu cần giảm c&aacute;c phản ứng phụ như đau v&agrave;/hoặc sốt. Cần b&aacute;o c&aacute;o t&aacute;c dụng phụ trực tiếp bằng c&aacute;ch truy cập v&agrave;o website<span class="Apple-converted-space">&nbsp;</span><a style="box-sizing: border-box; background-color: transparent; color: #337ab7; text-decoration-line: none; outline: none !important;" href="https://contactazmedical.astrazeneca.com/content/astrazeneca-champion/global/en/amp-form.html" target="_blank" rel="nofollow noopener noreferrer">https://contactazmedical.astrazeneca.com/</a>.</p>
                                    <h3 id="ftoc-heading-12" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 24px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">2. Vaccine Covid-19 c&oacute; phản ứng phụ l&acirc;u d&agrave;i n&agrave;o kh&ocirc;ng?</span></h3>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">V&igrave; vaccine Covid-19 l&agrave; vaccine mới, chưa c&oacute; dữ liệu nghi&ecirc;n cứu d&agrave;i hạn. Tuy nhi&ecirc;n,<span class="Apple-converted-space">&nbsp;</span><a style="box-sizing: border-box; background-color: transparent; color: #337ab7; text-decoration-line: none; outline: none !important;" href="https://vnvc.vn/astrazeneca/" target="_blank" rel="noopener noreferrer">COVID-19 Vaccine AstraZeneca</a>đ&atilde; được cung cấp cho h&agrave;ng ng&agrave;n người trong c&aacute;c thử nghiệm l&acirc;m s&agrave;ng. Họ đang v&agrave; sẽ được theo d&otilde;i cẩn thận trong 12 th&aacute;ng. dựa tr&ecirc;n ph&acirc;n t&iacute;ch sơ bộ từ dữ liệu gộp của bốn thử nghiệm l&acirc;m s&agrave;ng được tiến h&agrave;nh tại Vương quốc Anh, Brazil v&agrave; Nam Phi.</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Tại thời điểm ph&acirc;n t&iacute;ch, 23.745 người tham gia từ 18 tuổi trở l&ecirc;n đ&atilde; được ph&acirc;n nh&oacute;m ngẫu nhi&ecirc;n v&agrave; được ti&ecirc;m vaccine COVID-19 Vaccine AstraZeneca hoặc liều đối chứng. Trong số n&agrave;y, 12.021 người được ti&ecirc;m &iacute;t nhất một liều vaccine COVID-19 Vaccine AstraZeneca.</p>
                                    <h3 id="ftoc-heading-13" class="ftwp-heading" style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: 500; line-height: 1.1; color: #6d6e70; margin-top: 20px; margin-bottom: 10px; font-size: 24px; caret-color: #6d6e70; text-size-adjust: auto; text-align: justify;"><span style="box-sizing: border-box; font-weight: bold;">3. Vaccine c&oacute; ảnh hưởng đến khả năng sinh sản của t&ocirc;i kh&ocirc;ng?</span></h3>
                                    <p>&nbsp;</p>
                                    <p style="box-sizing: border-box; margin: 0px 0px 10px; caret-color: #6d6e70; color: #6d6e70; font-family: Arial, Helvetica, sans-serif; font-size: 16px; text-size-adjust: auto; text-align: justify;">Hiện tại, chưa c&oacute; dữ liệu nghi&ecirc;n cứu về ảnh hưởng của vaccine Covid-19 tr&ecirc;n khả năng sinh sản ở người. C&aacute;c thử nghiệm l&acirc;m s&agrave;ng tiếp theo đ&atilde; được l&ecirc;n kế hoạch v&agrave; th&ocirc;ng tin li&ecirc;n quan sẽ được cung cấp cho c&aacute;c b&aacute;c sĩ.</p>
                                    <p>&nbsp;</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <hr>
@endsection
